name: "Default (Generic)"
description: "Generic knowledge graph profile for any topic"
version: "2.0"

# No ontology section - the Claude Code skill auto-generates one
# based on the user's topic. This signals to the skill that
# ontology generation is needed.

parsing:
  system_message: "You are a knowledge extraction expert. Always respond with valid JSON."
  requirement_types: []
  deontic_modalities: []
  constraint_logic_types: []
  target_signal_examples: []
  scope_examples: []

id_patterns:
  patterns: {}
  authority_priorities: {}
  exclusions: []
  format_rules: {}

discovery:
  search_templates:
    - "<topic> comprehensive overview"
    - "<topic> official documentation"
    - "<topic> authoritative sources"
    - "<topic> key concepts and relationships"
    - "<topic> reference guide"
  sub_domains: []
  priority_tiers:
    P1:
      description: "Primary authoritative sources"
      depth: 3
      max_pages: 100
      delay: 1500
    P2:
      description: "Secondary documentation"
      depth: 2
      max_pages: 50
      delay: 1500
    P3:
      description: "Tutorials and guides"
      depth: 1
      max_pages: 25
      delay: 2000
    P4:
      description: "Community resources"
      depth: 1
      max_pages: 15
      delay: 2000
  gap_search_templates:
    - "<topic> <sub_domain> documentation"
    - "<topic> <sub_domain> guide reference"
  supplementary_sources: []
